# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dex < Formula
  desc "CLI tool for manipulating slide presentations"
  homepage "https://github.com/StephanSchmidt/dex"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StephanSchmidt/dex/releases/download/v0.1.0/dex_darwin_amd64.tar.gz"
      sha256 "003cfcee9a24bafa5804b84054965a2ef2a7f566e19e1a9a97c3711d1906353c"

      def install
        bin.install "dex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StephanSchmidt/dex/releases/download/v0.1.0/dex_darwin_arm64.tar.gz"
      sha256 "0d2e26aa74598c973102c686ad2f349f619c6c60df64651b4b88bceafbcdd83b"

      def install
        bin.install "dex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StephanSchmidt/dex/releases/download/v0.1.0/dex_linux_amd64.tar.gz"
      sha256 "1897764356d709eda2055ddecf94014fabe7b472989e1c635507f8b7f2fc5488"
      def install
        bin.install "dex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StephanSchmidt/dex/releases/download/v0.1.0/dex_linux_arm64.tar.gz"
      sha256 "d9bf5b70cac2a46a6195252c4583d0e71ca9d50832888eb99eafd6adb065b324"
      def install
        bin.install "dex"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dex --version")
  end
end
