# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dex < Formula
  desc "CLI tool for manipulating slide presentations"
  homepage "https://github.com/StephanSchmidt/dex"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StephanSchmidt/dex/releases/download/v0.3.0/dex_darwin_amd64.tar.gz"
      sha256 "9aacb9bd6dc60152e7d4fb5f6a912c7aa33c0bed76e8d33821a0af05a6c94067"

      define_method(:install) do
        bin.install "dex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StephanSchmidt/dex/releases/download/v0.3.0/dex_darwin_arm64.tar.gz"
      sha256 "f06ee1d322a738baa7d2ffcd3ccfda34546a6006eede3df6de16dde6d52fb612"

      define_method(:install) do
        bin.install "dex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StephanSchmidt/dex/releases/download/v0.3.0/dex_linux_amd64.tar.gz"
      sha256 "915d8f821bb8c446d9846990afa38b4fbeb45ec3eda2de99a7325ee890c42d3c"
      define_method(:install) do
        bin.install "dex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StephanSchmidt/dex/releases/download/v0.3.0/dex_linux_arm64.tar.gz"
      sha256 "9d1fc216473ddf096f372a3909b910eafaa4328691f3643d085fcc51ddb6d858"
      define_method(:install) do
        bin.install "dex"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dex --version")
  end
end
