# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dex < Formula
  desc "CLI tool for manipulating slide presentations"
  homepage "https://github.com/StephanSchmidt/dex"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StephanSchmidt/dex/releases/download/v0.2.0/dex_darwin_amd64.tar.gz"
      sha256 "efd4dc2db166026dc768e70de966deb515975c2b39e896ffcbd25677350d2cf7"

      def install
        bin.install "dex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/StephanSchmidt/dex/releases/download/v0.2.0/dex_darwin_arm64.tar.gz"
      sha256 "310cab8fb1468236e05f8968b9c2b1a934818d4846f35df6bb4061ac8207ebf3"

      def install
        bin.install "dex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/StephanSchmidt/dex/releases/download/v0.2.0/dex_linux_amd64.tar.gz"
      sha256 "bd373f9e1c719b8a882c9bab8eeb185b76025f8fe705c470958cc7a1ba3ca8b2"
      def install
        bin.install "dex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StephanSchmidt/dex/releases/download/v0.2.0/dex_linux_arm64.tar.gz"
      sha256 "f53a0897c6997e068b30d598f1c88c46017239a96354eb6aaec4a8987d5085d9"
      def install
        bin.install "dex"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dex --version")
  end
end
